-- Seed the curated mystique alias pool.
-- ON CONFLICT (name) DO NOTHING makes this safe to re-run; admins can
-- toggle individual aliases off via UPDATE alias_pool SET active = false.

INSERT INTO alias_pool (name, description) VALUES
  ('The Alchemist',       'Transmutes ordinary moments into meaning.'),
  ('The Mariner',         'Reads currents others miss; steady in open water.'),
  ('The Cartographer',    'Maps territory before walking it.'),
  ('The Architect',       'Designs from first principles, builds to last.'),
  ('The Curator',         'Selects with care; the room reflects their taste.'),
  ('The Storyteller',     'Holds the room; turns silence into narrative.'),
  ('The Diplomat',        'Finds the third option no one else saw.'),
  ('The Strategist',      'Three moves ahead, never showing the work.'),
  ('The Naturalist',      'At ease in wild places; reads weather and people alike.'),
  ('The Voyager',         'Restless in the best sense; collects perspectives.'),
  ('The Composer',        'Hears the whole arrangement before the first note.'),
  ('The Sculptor',        'Removes what doesn''t belong until the form emerges.'),
  ('The Gardener',        'Plants slowly; tends what they choose to keep.'),
  ('The Lighthouse',      'Visible from a distance; reliable in storms.'),
  ('The Falconer',        'Patient handler of fast, fierce things.'),
  ('The Linguist',        'Speaks the language of the room before the words.'),
  ('The Bibliophile',     'Lives in margins and end-papers.'),
  ('The Philosopher',     'Asks the question that reframes the conversation.'),
  ('The Astronomer',      'Long view; comfortable with what they cannot reach.'),
  ('The Archivist',       'Remembers what others forget to value.'),
  ('The Apothecary',      'Quiet expertise; small doses, large effects.'),
  ('The Vintner',         'Knows that good things take time and pressure.'),
  ('The Locksmith',       'Patient with closed things; never forces a turn.'),
  ('The Glassblower',     'Heat, breath, timing — works with what others find fragile.'),
  ('The Beekeeper',       'Calm around what stings; trusted by the swarm.'),
  ('The Cellist',         'Lower registers; carries the room without leading it.'),
  ('The Gambler',         'Reads odds and people; folds without regret.'),
  ('The Surveyor',        'Marks the land honestly; their lines hold up in court.'),
  ('The Provocateur',     'Asks the uncomfortable thing kindly.'),
  ('The Hermit',          'Solitude by choice, not absence; returns with something to say.'),
  ('The Conductor',       'Coordinates without commanding.'),
  ('The Negotiator',      'Walks away or stays — never bluffs.'),
  ('The Watchmaker',      'Believes in tolerances; respects small parts.'),
  ('The Fencer',          'Distance, timing, restraint.'),
  ('The Cinematographer', 'Frames a moment so you remember it later.'),
  ('The Lapidary',        'Polishes slowly; knows the difference between flaw and feature.'),
  ('The Tactician',       'Adapts the plan to the terrain, not the other way around.'),
  ('The Wanderer',        'Going somewhere; rarely says where.'),
  ('The Mystic',          'Comfortable with what they cannot prove.'),
  ('The Cipher',          'Reveals as much as the moment requires — no more.')
ON CONFLICT (name) DO NOTHING;
