-- Starter psychometric question bank (bank_version 1).
--
-- Representative set covering all four `question_type` shapes
-- (single / multi / scale / freeform) and the categories the matching pipeline
-- expects (values, attachment, communication, lifestyle, conflict). Extend
-- with a follow-up migration (0003_more_questions.sql) when the real bank is
-- finalised — DO NOT edit this file once it has shipped to prod, since the
-- migrator skips it by hash and edits will silently not apply.
--
-- Drizzle's migration runner guarantees this fires exactly once per env, so
-- no ON CONFLICT clause is needed. Categories are free-text (no enum), so
-- spelling matters — keep them lowercase and stable.

INSERT INTO psychometric_questions (prompt, question_type, options, scale_min, scale_max, category, weight) VALUES
  (
    'Which of these matters most to you in a long-term relationship?',
    'single',
    '["Emotional intimacy","Shared values","Physical attraction","Intellectual connection","Stability and trust"]'::jsonb,
    NULL, NULL,
    'values',
    3
  ),
  (
    'Pick up to three things you genuinely enjoy doing on a weekend.',
    'multi',
    '["Reading","Hiking or outdoors","Cooking","Live events or concerts","Quiet time alone","Traveling","Volunteering","Sports or fitness","Time with family"]'::jsonb,
    NULL, NULL,
    'lifestyle',
    1
  ),
  (
    'I find it easy to depend on the people closest to me.',
    'scale',
    NULL,
    1, 7,
    'attachment',
    2
  ),
  (
    'I worry that the people I love don''t feel as strongly about me as I do about them.',
    'scale',
    NULL,
    1, 7,
    'attachment',
    2
  ),
  (
    'When something is bothering me in a relationship, my first instinct is to:',
    'single',
    '["Bring it up directly that day","Wait for the right moment, then talk","Process it alone first","Hope it resolves itself"]'::jsonb,
    NULL, NULL,
    'communication',
    2
  ),
  (
    'In a disagreement, I focus on understanding before being understood.',
    'scale',
    NULL,
    1, 7,
    'conflict',
    2
  ),
  (
    'How important is it that your partner shares your faith or spiritual practice?',
    'scale',
    NULL,
    1, 5,
    'values',
    2
  ),
  (
    'In one or two sentences: what does a good Saturday with someone you love look like?',
    'freeform',
    NULL,
    NULL, NULL,
    'lifestyle',
    1
  );
