# syntax=docker/dockerfile:1.7

# ───────────────────────────────────────────────────────────────────────────
# 1) deps — install all dependencies (including dev) for the build stage.
#    pinned to the same Node major you develop on (22.x).
# ───────────────────────────────────────────────────────────────────────────
FROM node:22-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN corepack enable && \
    corepack prepare pnpm@latest --activate && \
    pnpm install --frozen-lockfile

# ───────────────────────────────────────────────────────────────────────────
# 2) builder — produce the Next.js standalone output.
#    The .env baked here is created by the workflow's "Copy the PROD_UI_ENV"
#    step before docker build runs. NEXT_PUBLIC_* values are inlined at
#    build time, so they must be present here.
# ───────────────────────────────────────────────────────────────────────────
FROM node:22-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN corepack enable && \
    corepack prepare pnpm@latest --activate && \
    pnpm build

# ───────────────────────────────────────────────────────────────────────────
# 3) runner — minimal production image.
#    Standalone output bundles only the modules actually imported, keeping
#    the final image small (~150–250 MB depending on lucide-react usage).
# ───────────────────────────────────────────────────────────────────────────
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Run as a non-root user. Next's standalone server expects to write to .next/cache.
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Migration runner: bring in the SQL files, the launcher script, and the
# drizzle-orm package (the standalone trace doesn't include the migrator
# submodule because the app itself never imports it).
COPY --from=builder --chown=nextjs:nodejs /app/db/migrations ./db/migrations
COPY --from=builder --chown=nextjs:nodejs /app/scripts/migrate.mjs ./scripts/migrate.mjs
COPY --from=deps    --chown=nextjs:nodejs /app/node_modules/drizzle-orm ./node_modules/drizzle-orm

USER nextjs

EXPOSE 3000

# server.js is generated by Next when output: "standalone" is set.
# Migrations are applied at container start (see docker-compose-dokploy.yml).
CMD ["node", "server.js"]
